#!/bin/sh

err() {
    exitval=$1
    shift
    echo -e "$*"
    # 1>&2
    exit $exitval
}

fqdn="$1"

[ ! -d "/usr/local/www" ] && mkdir -p /usr/local/www
cd /usr/local/www
mkdir data
chmod a+w data
